enum ContactVetMessageType {
  yes,
  ok,
  no,
  channelChoice,
  checkPhoneNumber,
  changePhoneNumber,
  emptyPhoneNumber,

  chat,
  email,
  sendEmail,
  phoneCall,
  videoCall,
  letsConnectChat,
  letsConnectEmail,
  letsConnectVideoOrPhone,
  letsConnectVideoOrPhoneInformation,
  noThanks,
}
